     <div class="navbar navbar-default navbar-static-bottom" id="footer">
    	<div class="container">
			<div class="social-network">
            		<h3 class="navbar-text" style="font-size: 21px;font-weight: bold;color: #16becf;margin-top: 8px;margin-bottom: 8px;
">Join Us On : </h3>
                <a href="https://www.facebook.com/pages/Family2Family/820471384696590" target="_blank"><img src="img/Fb_icon.png" class="img-responsive" style="display:inline;margin-right:10px;"/></a>
                <a href="https://twitter.com/Family_Family2" target="_blank"><img src="img/Twitter_icon.png" class="img-responsive" style="display:inline;"/></a>
            </div>
        	<p class="navbar-text pull-left">Copyright © Family to Family. All rights reserved.</p>
        </div>
    </div>